### ISSUE TITLE
Context Search not working with OSE 1.95.7

### ISSUE THREAD

**Issue by buthub** [Baton34/organize-search-engines#100]
Hi, I updated OSE to 1.95.7 on my 50.1.0 Firefox and noticed that the Context Search add-on was no longer working properly.
https://addons.mozilla.org/en-US/firefox/addon/context-search/?src=api

It would no longer keep the subfolder structure; instead, all search engines were together in one long list.  It was working with the last version, organize-search-engines_1.95.2-fx.

Another very, very small bug.  If you've selected 'Open All in Tabs' in one of your search engine folders and close FF, when you reopen FF, it doesn't remember what you had selected.  It just reverts to a single search engine.

Thanks for the great work in updating this, Baton34!

**Comment by Baton34** [comment]
> Context Search add-on was no longer working properly
fixed in 1.95.8
> FF, it doesn't remember what you had selected
does it worked on old ff or ose version?

**Comment by PlaceboPRS** [comment]
I have a possibly similar issue with a similar addon, Enhanced Middle Click https://addons.mozilla.org/en-US/firefox/addon/enhanced-middle-click/?src=api if I have a folder of searches chosen in the search bar and then middle click a highlighted word it only searches using the first search engine from within the folder.

**Comment by buthub** [comment]
Thanks, Baton34.  Sorry to take so long to get back to you.

- FF, it doesn't remember what you had selected
does it worked on old ff or ose version?

It hasn't worked in a long while, from previous FF or OSE versions, and still doesn't with the latest 1.95.9.  

Also, there's another bug with regards to renaming the search engines.  When you close and re-open it, the new name doesn't stick.  It just goes back to the old one.  Seems to work sometimes...  not sure what the conditions are though.

**Comment by Baton34** [comment]
**PlaceboPRS**
I cant add compatibility with Enhanced Middle Click to OSE, not my coding level, sorry.
**buthub**
> FF, it doesn't remember what you had selected
When you press 'Open All in Tabs' OSE creates temporary search engine in memory and it must not be saved, because in this way it generates new engine in list.
